name: example_app
description: A new Flutter project.
version: 2.0.3+3

publish_to: none

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  rounded_loading_button:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
